context:
  thead:
    -
      text: Head 1
  tbody:
    -
      rows:
        -
          text: Anim
        -
          text: Consectetur
        -
          text: Laboris
        -
          text: Consectetur
        -
          text: Minim
  tfoot:
    -
      text: Foot 1