context:
  text: Ex Esse
  pill: false
  modifier: light

variants:
  -
    name: primary
    context:
      modifier: primary
  -
    name: secondary
    context:
      modifier: secondary
  -
    name: success
    context:
      modifier: success
  -
    name: danger
    context:
      modifier: danger
  -
    name: warning
    context:
      modifier: warning
  -
    name: info
    context:
      modifier: info
  -
    name: light
    context:
      modifier: light
  -
    name: dark
    context:
      modifier: dark
  -
    name: pill
    context:
      pill: true
      modifier: primary