order: 0
collated: true
context:
  tag: h1
  text: Heading One

variants:
  -
    name: h2
    context:
      tag: h2
      text: Heading Two
  -
    name: h3
    context:
      tag: h3
      text: Heading Three
  -
    name: h4
    context:
      tag: h4
      text: Heading Four
  -
    name: h5
    context:
      tag: h5
      text: Heading Five
  -
    name: h6
    context:
      tag: h6
      text: Heading Six
    