context:
    src: //placehold.co/800x450?text=16:9
    alt: 16x9
    cap: '<strong>Caption:</strong> Mollit mollit ipsum qui anim adipisicing fugiat tempor tempor reprehenderit esse mollit ullamco.'

variants:
    -
        name: 16x9
        context:
            src: //placehold.co/800x450?text=16:9
            alt: 16x9
            cap: null
    -
        name: 1x1
        context:
            src: //placehold.co/400x400?text=1:1
            alt: 1x1
            cap: null
    -
        name: 3x2
        context:
            src: //placehold.co/540x360?text=3:2
            alt: 3x2
            cap: null
    -
        name: 4x3
        context:
            src: //placehold.co/512x384?text=4:3
            alt: 4x3
            cap: null
    -
        name: responsive
        context:
            src: //placehold.co/1600x900?text=16:9
            alt: 16x9
            cap: null
            modifier: responsive
