context:
  quote: '&ldquo;Eu exercitation ea eu esse qui qui proident sint eiusmod irure mollit tempor tempor. Pariatur pariatur ipsum mollit exercitation Lorem non do ad do excepteur!&rdquo;'
  # citation:
  #   url: '#'
  #   text: Reprehenderit Labore sunt Fugiat
  author: Quis Aliquip