context:
    tag: a
    text: Cupidatat fugiat ex
    href: '#'
    modifier: null
variants:
    -
        name: primary
        context:
            text: Non ea enim
            modifier: primary
    -
        name: secondary
        context:
            text: Occaecat labore
            modifier: secondary
    -
        name: success
        context:
            text: Non ea enim
            modifier: success
    -
        name: warning
        context:
            text: Non ea enim
            modifier: warning
    -
        name: danger
        context:
            text: Non ea enim
            modifier: danger
    -
        name: info
        context:
            text: Non ea enim
            modifier: info
    -
        name: icon
        context:
            text: null
            icon: true
            modifier: icon btn--primary
    -
        name: icon-left
        context:
            iconLeft: true
            modifier: primary
    -
        name: icon-right
        context:
            iconRight: true
            modifier: primary