context:
    players:
        -
            username: IdCulpa
        -
            username: Consectetur
        -
            username: LaborumMagna
        -
            username: eiusmod
        -
            username: Veniam
        -
            username: Adipisicing
        -
            username: dolore
        -
            username: pariatur
        -
            username: laboris
