context:
    icon: mdi-cards-playing
    family: mdi
variants:
    -
        name: spin
        context:
            modifier: mdi-spin
    -
        name: flip-h
        context:
            modifier: mdi-flip-h
    -
        name: flip-v
        context:
            modifier: mdi-flip-v
    -
        name: rotate-45
        context:
            modifier: mdi-rotate-45
    -
        name: rotate-90
        context:
            modifier: mdi-rotate-90
    -
        name: rotate-135
        context:
            modifier: mdi-rotate-135
    -
        name: rotate-180
        context:
            modifier: mdi-rotate-180
    -
        name: rotate-225
        context:
            modifier: mdi-rotate-225
    -
        name: rotate-270
        context:
            modifier: mdi-rotate-270
    -
        name: rotate-315 
        context:
            modifier: mdi-rotate-315
