collated: true
context:
  tag: p
  text: Adipisicing fugiat aliqua enim magna. Mollit reprehenderit culpa exercitation non aliquip qui quis. Aliqua et veniam est occaecat adipisicing ut proident nisi nostrud eu culpa laboris ipsum amet. Nostrud mollit consequat dolore non est magna duis non nostrud non voluptate amet nostrud. Veniam excepteur proident irure cupidatat commodo nulla commodo. Irure quis anim aute anim esse. Eiusmod aliquip aliqua enim ut excepteur officia cupidatat mollit pariatur pariatur Lorem.
  type: base
variants:
  - name: Lead
    context:
      text: Ullamco consequat labore fugiat ad enim. Amet aute ex nostrud voluptate consequat reprehenderit aute non fugiat in esse ut officia. Esse ea nostrud sint ut in sint ex sit exercitation enim duis. Ut et adipisicing minim ex excepteur aute amet adipisicing Lorem laborum quis occaecat. Deserunt adipisicing elit ullamco aliquip. Qui dolor dolore eiusmod consectetur commodo laborum laboris quis. Nulla do laboris ullamco id amet non elit enim sit duis minim adipisicing cillum.
      type: lead
  - name: Small
    context:
      text: Anim et aliqua ex aliqua fugiat dolor aute anim quis do ea ex sunt. Cupidatat in et ullamco ut qui commodo ad esse eu ad. Duis Lorem est cillum incididunt magna reprehenderit excepteur. Adipisicing elit cillum commodo qui ex nostrud. Elit exercitation sit culpa eiusmod nulla anim. Ex ad id amet nostrud aliquip nisi ullamco reprehenderit do est amet laborum do. Fugiat cupidatat aute anim cillum laborum nisi voluptate. Sunt Lorem exercitation non commodo id commodo. Amet irure consectetur cupidatat voluptate culpa.
      type: small