context:
    title: Pokernicus BOUNTY HUNT!
    location: Grant's Tavern
    address: 1234 W Fifth Stree, Denver, CO 80204
    capacity:
    game:
    start:
    end:
    button:
        href: '/components/detail/event'
