order: -1
context:
  src: //via.placeholder.com/800x450.png
  alt: logo
variants:
  - name: Web Logo
    context:
      src: //via.placeholder.com/200x112.png
      alt: web logo
  - name: App Logo
    context:
      src: //via.placeholder.com/200x200.png
      alt: app logo
  - name: Favicon
    context:
      src: //via.placeholder.com/32x32.png
      alt: favicon