context:
    form:
        fields:
            -
                label:
                    id: firstName
                    text: First Name
                input:
                    id: firstName
                    type: text
            -
                label:
                    id: lastName
                    text: Last Name
                input:
                    id: lastName
                    type: text
            -
                label:
                    id: dob
                    text: Date of Birth
                input:
                    id: dob
                    type: date
            -
                label:
                    id: email
                    text: E-mail
                input:
                    id: email
                    type: email
            -
                label:
                    id: username
                    text: Username
                input:
                    id: username
                    type: text
                    maxlength: 32
            -
                label:
                    id: password
                    text: Password
                input:
                    id: password
                    type: password
            -
                label: false
                input: false
                button:
                    text: Sign Up
                    modifier: success
                    iconRight:
                        icon: arrow-right

