order: 2
collated: true
context:
  fg: black
  hex: white
  var: white
  rgb: (255,255,255)
  modifier: white
variants:
  - name: black
    context:
      fg: white
      hex: black
      var: black
      rgb: (0,0,0)
      modifier: black
  - name: primary
    context:
      fg: white
      hex: blue
      var: blue
      rgb: (0,0,0)
      modifier: primary
  - name: secondary
    context:
      fg: white
      hex: purple
      var: purple
      rgb: (0,0,0)
      modifier: secondary
  - name: success
    context:
      fg: white
      hex: green
      var: green
      rgb: (0,0,0)
      modifier: success
  - name: warning
    context:
      fg: black
      hex: yellow
      var: yellow
      rgb: (0,0,0)
      modifier: warning
  - name: danger
    context:
      fg: white
      hex: red
      var: red
      rgb: (0,0,0)
      modifier: danger