order: -1
collated: true
context:
  color: default
  material:
    name: blue-grey
    val: 200

variants:
  -
    name: primary
    context:
      color: primary
      material:
        name: blue
        val: 700
  -
    name: secondary
    context:
      color: secondary
      material:
        name: deep-purple
        val: 400
  -
    name: success
    context:
      color: success
      material:
        name: green
        val: 400
  -
    name: warning
    context:
      color: warning
      material:
        name: yellow
        val: 400
  -
    name: danger
    context:
      color: danger
      material:
        name: red
        val: 400
  -
    name: info
    context:
      color: info
      material:
        name: blue
        val: 400