context:
  form:
    -
      col: 4
      name: firstName
      label:
        text: First Name
    -
      col: 4
      name: lastName
      label:
        text: Last Name
    -
      col: 4
      name: dob
      input:
        type: date
      label:
        text: Date of Birth
    -
      col: 12
      name: email
      input:
        type: email
      label:
        text: E-mail Address
    -
      col: 12
      name: username
      label:
        text: Username