context:
    image:
        src: https://via.placeholder.com/200x170.png
        alt: Card Image
    title: Cupidatat proident dolore
    text: Consectetur excepteur tempor dolor dolor duis officia sunt consequat magna. Ea culpa laboris mollit minim nisi incididunt dolor. Mollit elit Lorem est reprehenderit duis nulla aliqua ipsum incididunt.
