context:
  fields:
    -
      id: firstName
      name: firstName
      type: text
      label: First Name
      autocomplete: off
      columns:
        - sm-12
        - md-6
    -
      id: lastName
      name: lastName
      type: text
      label: Last Name
      autocomplete: off
      columns:
        - sm-12
        - md-6
    -
      id: username
      name: username
      type: text
      label: Username
      autocomplete: off
      columns:
        - sm-12
        - md-6
    -
      id: email
      name: email
      type: email
      label: E-mail Address
      autocomplete: off
      columns:
        - sm-12
        - md-6
    -
      id: dob
      name: dob
      type: date
      label: Date of Birth
      autocomplete: off
      columns:
        - sm-12
        - md-6
    
