context:
    margin: 3
    inline: false
    floating: false
    label:
        id: input
    input:
        id: input
variants:
    -
        name: inline
        context:
            inline: true
            label:
                class: mb-0
    -
        name: floating
        context:
            floating: true
            label:
                floating: true
