context:
    margin: 3
    inline: false
    floating: false
    label:
        id: input
        text: Pariatur dolor

    input:
        id: input
        type: text
variants:
    -
        name: inline
        context:
            inline: true
            label:
                class: mb-0
            input:
                type: date
    -
        name: floating
        context:
            floating: true
            label:
                floating: true
            