context:
    tag: a
    href: '#'
    type: null
    text: Duis nulla Cillum
    icon: null
    iconLeft: null
    iconRight: null
    modifier: link

variants:
    -
        name: primary
        context:
            modifier: primary
    -
        name: secondary
        context:
            modifier: secondary
    -
        name: success
        context:
            modifier: success
    -
        name: danger
        context:
            modifier: danger
    -
        name: warning
        context:
            modifier: warning
    -
        name: info
        context:
            modifier: info
    -
        name: light
        context:
            modifier: light
    -
        name: dark
        context:
            modifier: dark
    -
        name: icon
        context:
            icon: true
            text: null
            class: btn-icon
            modifier: primary
    -
        name: disabled
        context:
            disabled: true
            modifier: primary
