context:
    label:
        text: Irure aliqua magna
        class: form-control__label
        forId: input
    input:
        id: input
        class: form-control__input
variants:
    -
        name: horizontal
        context:
            modifier: horizontal
